#! /bin/sh

set -e

DESC="vsftpd"
NAME=vsftpd
DAEMON=/usr/sbin/$NAME

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon -S --pidfile /var/run/vsftpd.local -m -b -a $NAME -- /etc/vsftpd-local.conf
	echo "OK"
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K --pidfile /var/run/vsftpd.local
	echo "OK"
	;;
  restart|force-reload)
	echo "Restarting $DESC: "
	$0 stop
	sleep 1
	$0 start
	echo ""
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
