#! /bin/sh

set -e

DESC="gpsreader"
NAME=gpsreader-arm
DAEMON=/opt/$NAME

source /etc/sysvars
case "$1" in
  start)
	echo -n "Starting $DESC: "
	logger "$DESC started"
	start-stop-daemon -S --pidfile /var/run/$NAME -m -a $DAEMON -- -i $GPS_INTERVAL &
	echo "OK"
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K --pidfile /var/run/$NAME
	logger "$DESC stopped"
	echo "OK"
	;;
  restart|force-reload)
	echo "Restarting $DESC: "
	$0 stop
	sleep 1
	$0 start
	echo ""
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

