#!/bin/sh

set -e

DESC="sender"
NAME=sender-arm
DAEMON=/opt/$NAME

source /etc/sysvars

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon -S --pidfile /var/run/$NAME -m -a $DAEMON -- -i $SENDER_INTERVAL -k $SENDER_KEY -l 50 &
	logger "$DESC started"
	echo "OK"
	;;
  stop)
	echo -n "Stopping $DESC: "
	logger "$DESC stopped"
	start-stop-daemon -K --pidfile /var/run/$NAME
	killall $NAME
	echo "OK"
	;;
  restart|force-reload)
	echo "Restarting $DESC: "
	$0 stop
	sleep 1
	$0 start
	echo ""
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

